apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    klovercloud-workflow-hub/category: 'ARGO'
  name: klovercloud-image-scanner
spec:
  templates:
    # trivy image quay.io/<username>/<image-name>:<tag>
    - name: trivy-docker-image-scanner
      inputs:
        parameters:
          - name: IMAGE_NAME # Required
          - name: IMAGE_VERSION_TAG
          - name: REGISTRY_USERNAME  # Optional, Required if registry is private
          - name: REGISTRY_PASSWORD   # Optional, Required if registry is private
      container:
        image: aquasec/trivy
        command: [trivy, image, "{{inputs.parameters.REGISTRY_USERNAME}}/{{inputs.parameters.IMAGE_NAME}}:{{inputs.parameters.IMAGE_VERSION_TAG}}"]
        env:
          - name: TRIVY_USERNAME
            value: "{{inputs.parameters.REGISTRY_USERNAME}}"
          - name: TRIVY_PASSWORD
            value: "{{inputs.parameters.REGISTRY_PASSWORD}}"

    # trivy image quay.io/<organization>/<image-name>:<tag> OR
    # trivy image quay.io/<user_name>/<image-name>:<tag>
    - name: trivy-quay-image-scanner
      inputs:
        parameters:
          - name: IMAGE_NAME # Required
          - name: IMAGE_VERSION_TAG
          - name: REGISTRY_USERNAME  # Optional, Required if registry is private
          - name: REGISTRY_PASSWORD   # Optional, Required if registry is private
      container:
        image: aquasec/trivy
        command: [trivy, image, "quay.io/{{inputs.parameters.REGISTRY_USERNAME}}/{{inputs.parameters.IMAGE_NAME}}:{{inputs.parameters.IMAGE_VERSION_TAG}}"]
        env:
          - name: TRIVY_USERNAME
            value: "{{inputs.parameters.REGISTRY_USERNAME}}"
          - name: TRIVY_PASSWORD
            value: "{{inputs.parameters.REGISTRY_PASSWORD}}"

      # trivy image <harbor-registry-url>/<project-name>/<image-name>:<tag>
    - name: trivy-harbor-image-scanner
      inputs:
        parameters:
          - name: HARBOR_REGISTRY_SERVER_URL
          - name: PROJECT_NAME
          - name: IMAGE_NAME # Required
          - name: IMAGE_VERSION_TAG
          - name: REGISTRY_USERNAME  # Optional, Required if registry is private
          - name: REGISTRY_PASSWORD   # Optional, Required if registry is private
      container:
        image: aquasec/trivy
        command: [trivy, image, "{{inputs.parameters.HARBOR_REGISTRY_SERVER_URL}}/{{inputs.parameters.PROJECT_NAME}}/{{inputs.parameters.IMAGE_NAME}}:{{inputs.parameters.IMAGE_VERSION_TAG}}"]
        env:
          - name: TRIVY_USERNAME
            value: "{{inputs.parameters.REGISTRY_USERNAME}}"
          - name: TRIVY_PASSWORD
            value: "{{inputs.parameters.REGISTRY_PASSWORD}}"