apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    klovercloud-workflow-hub/category: 'ARGO'
  name: klovercloud-deployment-trigger
spec:
  templates:
    - name: basic-trigger
      inputs:
        parameters:
          - name: PUT_REQUEST_URL # Required
          - name: GET_REQUEST_URL # Required
      container:
        image: quay.io/klovercloud/service:klovercloud-deployment-trigger-v0.0.4-dev
        env:
          - name: GET_REQUEST_URL
            value: "{{inputs.parameters.GET_REQUEST_URL}}"
          - name: PUT_REQUEST_URL
            value: "{{inputs.parameters.PUT_REQUEST_URL}}"